import { spawnSync } from 'child_process'
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const cwd = process.cwd()
const depsDir = join(cwd, 'node_modules/.vite/deps')
const reactFile = join(depsDir, 'react.js')

function optimizeDeps() {
  const result = spawnSync('npx', ['vite', 'optimize', '--force'], {
    stdio: 'inherit',
    cwd
  })

  if (result.status !== 0) {
    console.error('Failed to pre-optimize dependencies')
    process.exit(result.status ?? 1)
  }
}

function patchReactStub() {
  if (!existsSync(reactFile)) {
    console.warn('react.js was not generated by Vite; skipping patch')
    return
  }

  const current = readFileSync(reactFile, 'utf8')
  if (current.trim() && !current.trim().startsWith('//# sourceMappingURL')) {
    return
  }

  const chunkFiles = readdirSync(depsDir)
    .filter((file) => file.startsWith('chunk-') && file.endsWith('.js'))

  if (chunkFiles.length === 0) {
    console.warn('No Vite chunk files found; skipping react.js patch')
    return
  }

  let reactChunk = null
  for (const chunk of chunkFiles) {
    const content = readFileSync(join(depsDir, chunk), 'utf8')
    if (content.includes('var require_react = __commonJS')) {
      reactChunk = chunk
      break
    }
  }

  if (!reactChunk) {
    console.warn('Could not locate chunk exporting require_react; skipping react.js patch')
    return
  }

  const importLines = chunkFiles.map((chunk) => {
    if (chunk === reactChunk) {
      return `import { require_react } from "./${chunk}";`
    }
    return `import "./${chunk}";`
  })

  const patched = `${importLines.join('\n')}\nexport default require_react();\nexport { require_react };\n`
  writeFileSync(reactFile, patched)
  console.log('Patched Vite pre-bundled react.js stub')
}

optimizeDeps()
patchReactStub()
